version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/level3_nlp_finalproject-nlp-01
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu
